### ISSUE TITLE
`registry:delete` command to delete an event type

### ISSUE THREAD

**Issue by mattbishop** [evently-cloud/cli#19]
The opposite of `new`, it will delete the event type from the registry. If an event of this type has been appended to the ledger, the command will fail.

**Comment by evert** [comment]
For this we could either do:

```
evently registry:delete -e entityname -n eventname
```

Or 

```
evently registry:delete -e entityname/eventname
```

**Comment by mattbishop** [comment]
Let's keep -e -n pattern, someone might use a slash as an entity name.
