### ISSUE TITLE
Create a Linux/MacOS installation step

### ISSUE THREAD

**Issue by mattbishop** [evently-cloud/cli#2]
This may be as simple as testing `./install.sh` and creating a curl | bash command to instruct users how to pull the script and run it.

Look to Heroku for the dev experience.

**Comment by mattbishop** [comment]
My main concern will be for the non-JS developers who won't have node on their machines. It's why I like the heroku approach in that it downloads the node binary and uses it instead of what's on the path.

I have been the frustrated user of CLI tools that require a runtime to already be installed. It is too much to ask IMO, especially for the .NET developer community.

For MacOS/Linux we can probably get by with requiring something like `curl https://cli.evently.cloud/install.sh | sh` or similar. Also, I have a backblaze account set up to store things.

**Comment by mattbishop** [comment]
Here is the Heroku installation page, for reference: https://devcenter.heroku.com/articles/heroku-cli

**Comment by evert** [comment]
Based on our discussion, we're canning this *for now* and start with just running this with `npx`. In the future we'll figure out what a good next platform to support is, which may be `brew`, `snap`, `flatpak` or `apt` depending on what's deemed the highest priority.
