### ISSUE TITLE
`registry:list` to list entities, and events

### ISSUE THREAD

**Issue by mattbishop** [evently-cloud/cli#20]
This may take a little thinking, but we want to show all the events registered for an entity, and another command to list the entities themselves. For larger systems with hundreds of events, a full list gets to be difficult to use.

**Comment by evert** [comment]
Some ideas for the interface, let me now what you think:

```
# Show all entities
evently registry:list-entities
```

```
# Show all entities for an event
evently registry:list-events --entity foo
evently registry:list-events -e foo
```

Perhaps all these commands can have a `-v` for verbose flag that shows the name + the URI ?

**Comment by evert** [comment]
@mattbishop Does the above syntax work for you?

**Comment by mattbishop** [comment]
LGTM
