### ISSUE TITLE
GitHub releases to match NPM releases

### ISSUE THREAD

**Issue by mattbishop** [evently-cloud/cli#27]
Is there an automated way to publish a GitHub release along with an npm release? People will want to see the changes in each release.

**Comment by mattbishop** [comment]
Is there an automated way to publish a GitHub release along with an npm release? People will want to see the changes in each release.

**Comment by evert** [comment]
I have some automation that automatically does the publish to npm when a github release is created. Can set that up here too. I would either need admin access to the repo, or you'll need to setup some secrets to make this work.

**Comment by evert** [comment]
Done this, and also opened #32 as a follow-up
