### ISSUE TITLE
Thought: remove --token global argument

### ISSUE THREAD

**Issue by evert** [evently-cloud/cli#45]
Hey I thought it might be nice to drop the `--token` argument, given that a custom token can also be provided on the command-line like this:

    EVENTLY_TOKEN=foo evently register:list-entities

instead of

    evently register:list-entities --token foo

My only reason is that it adds some clutter to every command file, and help output.

**Comment by mattbishop** [comment]
Authentication is going to change in the future to be more like Heroku works, where one signs in with an account and the token is stored. Selfishly, I like `--token` because in developing Evently, I can switch to different environments  without changing the env var.

**Comment by evert** [comment]
Sounds good!
